// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canvas.sql

package db

import (
	"context"
)

const canvasCountOrganizations = `-- name: CanvasCountOrganizations :one

SELECT COUNT(*) FROM organizations
`

// Canvas area: projects, environments, variables, the cluster row it reads.
// Creation order is rowid order (insertion order; an UPDATE keeps the rowid).
func (q *Queries) CanvasCountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, canvasCountOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const canvasDeleteNodeVariables = `-- name: CanvasDeleteNodeVariables :exec
DELETE FROM variables WHERE node_id = ?
`

func (q *Queries) CanvasDeleteNodeVariables(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, canvasDeleteNodeVariables, nodeID)
	return err
}

const canvasDeleteVariable = `-- name: CanvasDeleteVariable :exec
DELETE FROM variables WHERE id = ?
`

func (q *Queries) CanvasDeleteVariable(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, canvasDeleteVariable, id)
	return err
}

const canvasGetClusterServers = `-- name: CanvasGetClusterServers :many
SELECT servers FROM cluster WHERE id = 1
`

func (q *Queries) CanvasGetClusterServers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, canvasGetClusterServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var servers int64
		if err := rows.Scan(&servers); err != nil {
			return nil, err
		}
		items = append(items, servers)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canvasGetProjectBySlug = `-- name: CanvasGetProjectBySlug :one
SELECT id, organization_id, name, slug, created_at FROM projects WHERE organization_id = ? AND slug = ?
`

type CanvasGetProjectBySlugParams struct {
	OrganizationID string
	Slug           string
}

func (q *Queries) CanvasGetProjectBySlug(ctx context.Context, arg CanvasGetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, canvasGetProjectBySlug, arg.OrganizationID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const canvasInsertEnvironment = `-- name: CanvasInsertEnvironment :exec
INSERT INTO environments (id, project_id, name, is_production, created_at) VALUES (?, ?, ?, ?, ?)
`

type CanvasInsertEnvironmentParams struct {
	ID           string
	ProjectID    string
	Name         string
	IsProduction int64
	CreatedAt    int64
}

func (q *Queries) CanvasInsertEnvironment(ctx context.Context, arg CanvasInsertEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, canvasInsertEnvironment,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.IsProduction,
		arg.CreatedAt,
	)
	return err
}

const canvasInsertProject = `-- name: CanvasInsertProject :exec
INSERT INTO projects (id, organization_id, name, slug, created_at) VALUES (?, ?, ?, ?, ?)
`

type CanvasInsertProjectParams struct {
	ID             string
	OrganizationID string
	Name           string
	Slug           string
	CreatedAt      int64
}

func (q *Queries) CanvasInsertProject(ctx context.Context, arg CanvasInsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, canvasInsertProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const canvasInsertVariable = `-- name: CanvasInsertVariable :exec
INSERT INTO variables (id, node_id, key, value, secret) VALUES (?, ?, ?, ?, ?)
`

type CanvasInsertVariableParams struct {
	ID     string
	NodeID string
	Key    string
	Value  string
	Secret int64
}

func (q *Queries) CanvasInsertVariable(ctx context.Context, arg CanvasInsertVariableParams) error {
	_, err := q.db.ExecContext(ctx, canvasInsertVariable,
		arg.ID,
		arg.NodeID,
		arg.Key,
		arg.Value,
		arg.Secret,
	)
	return err
}

const canvasListEnvironmentVariables = `-- name: CanvasListEnvironmentVariables :many
SELECT v.id, v.node_id, v."key", v.value, v.secret FROM variables v JOIN nodes n ON n.id = v.node_id
WHERE n.environment_id = ? ORDER BY v.rowid
`

func (q *Queries) CanvasListEnvironmentVariables(ctx context.Context, environmentID string) ([]Variable, error) {
	rows, err := q.db.QueryContext(ctx, canvasListEnvironmentVariables, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variable{}
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Key,
			&i.Value,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canvasListEnvironments = `-- name: CanvasListEnvironments :many
SELECT id, project_id, name, is_production, created_at FROM environments WHERE project_id = ? ORDER BY rowid
`

func (q *Queries) CanvasListEnvironments(ctx context.Context, projectID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, canvasListEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IsProduction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canvasListProjects = `-- name: CanvasListProjects :many
SELECT id, organization_id, name, slug, created_at FROM projects WHERE organization_id = ? ORDER BY rowid
`

func (q *Queries) CanvasListProjects(ctx context.Context, organizationID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, canvasListProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canvasListVariables = `-- name: CanvasListVariables :many
SELECT id, node_id, "key", value, secret FROM variables WHERE node_id = ? ORDER BY rowid
`

func (q *Queries) CanvasListVariables(ctx context.Context, nodeID string) ([]Variable, error) {
	rows, err := q.db.QueryContext(ctx, canvasListVariables, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variable{}
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Key,
			&i.Value,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canvasMarkDirty = `-- name: CanvasMarkDirty :exec
UPDATE nodes SET dirty = 1 WHERE id = ?
`

func (q *Queries) CanvasMarkDirty(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, canvasMarkDirty, id)
	return err
}

const canvasUpdateVariable = `-- name: CanvasUpdateVariable :execrows
UPDATE variables SET key = ?2, value = ?3, secret = ?4 WHERE id = ?1
`

type CanvasUpdateVariableParams struct {
	ID     string
	Key    string
	Value  string
	Secret int64
}

func (q *Queries) CanvasUpdateVariable(ctx context.Context, arg CanvasUpdateVariableParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, canvasUpdateVariable,
		arg.ID,
		arg.Key,
		arg.Value,
		arg.Secret,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
