// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy.sql

package db

import (
	"context"
)

const deployDeleteSteps = `-- name: DeployDeleteSteps :exec
DELETE FROM deployment_steps WHERE deployment_id = ?
`

func (q *Queries) DeployDeleteSteps(ctx context.Context, deploymentID string) error {
	_, err := q.db.ExecContext(ctx, deployDeleteSteps, deploymentID)
	return err
}

const deployGet = `-- name: DeployGet :one
SELECT id, environment_id, sha, message, status, started_at, finished_at FROM deployments WHERE id = ?
`

func (q *Queries) DeployGet(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, deployGet, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Sha,
		&i.Message,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deployGetCluster = `-- name: DeployGetCluster :one
SELECT servers FROM cluster WHERE id = 1
`

func (q *Queries) DeployGetCluster(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, deployGetCluster)
	var servers int64
	err := row.Scan(&servers)
	return servers, err
}

const deployHasRunning = `-- name: DeployHasRunning :one

SELECT COUNT(*) FROM deployments WHERE environment_id = ? AND status = 'running'
`

// Deployments, their steps and log, and the cluster row. Owner: the deploy area.
// "Newest" is creation order: started_at, then rowid (insertion order) for ties.
func (q *Queries) DeployHasRunning(ctx context.Context, environmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deployHasRunning, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deployInsert = `-- name: DeployInsert :exec
INSERT INTO deployments (id, environment_id, sha, message, status, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type DeployInsertParams struct {
	ID            string
	EnvironmentID string
	Sha           *string
	Message       string
	Status        string
	StartedAt     int64
	FinishedAt    *int64
}

func (q *Queries) DeployInsert(ctx context.Context, arg DeployInsertParams) error {
	_, err := q.db.ExecContext(ctx, deployInsert,
		arg.ID,
		arg.EnvironmentID,
		arg.Sha,
		arg.Message,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const deployInsertLog = `-- name: DeployInsertLog :exec
INSERT INTO deployment_log (deployment_id, at, node_id, text) VALUES (?, ?, ?, ?)
`

type DeployInsertLogParams struct {
	DeploymentID string
	At           int64
	NodeID       *string
	Text         string
}

func (q *Queries) DeployInsertLog(ctx context.Context, arg DeployInsertLogParams) error {
	_, err := q.db.ExecContext(ctx, deployInsertLog,
		arg.DeploymentID,
		arg.At,
		arg.NodeID,
		arg.Text,
	)
	return err
}

const deployInsertStep = `-- name: DeployInsertStep :exec
INSERT INTO deployment_steps (deployment_id, idx, node_id, label, status, started_at, applied_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type DeployInsertStepParams struct {
	DeploymentID string
	Idx          int64
	NodeID       *string
	Label        string
	Status       string
	StartedAt    *int64
	AppliedAt    *int64
	FinishedAt   *int64
}

func (q *Queries) DeployInsertStep(ctx context.Context, arg DeployInsertStepParams) error {
	_, err := q.db.ExecContext(ctx, deployInsertStep,
		arg.DeploymentID,
		arg.Idx,
		arg.NodeID,
		arg.Label,
		arg.Status,
		arg.StartedAt,
		arg.AppliedAt,
		arg.FinishedAt,
	)
	return err
}

const deployLatest = `-- name: DeployLatest :one
SELECT id, environment_id, sha, message, status, started_at, finished_at FROM deployments WHERE environment_id = ?
ORDER BY started_at DESC, rowid DESC LIMIT 1
`

func (q *Queries) DeployLatest(ctx context.Context, environmentID string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, deployLatest, environmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Sha,
		&i.Message,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deployListLog = `-- name: DeployListLog :many
SELECT seq, deployment_id, at, node_id, text FROM deployment_log WHERE deployment_id = ? ORDER BY seq
`

func (q *Queries) DeployListLog(ctx context.Context, deploymentID string) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, deployListLog, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.Seq,
			&i.DeploymentID,
			&i.At,
			&i.NodeID,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployListOrganizationIDs = `-- name: DeployListOrganizationIDs :many
SELECT id FROM organizations ORDER BY created_at, id
`

func (q *Queries) DeployListOrganizationIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deployListOrganizationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployListRecent = `-- name: DeployListRecent :many
SELECT id, environment_id, sha, message, status, started_at, finished_at FROM deployments WHERE environment_id = ?
ORDER BY started_at DESC, rowid DESC LIMIT ?
`

type DeployListRecentParams struct {
	EnvironmentID string
	Limit         int64
}

func (q *Queries) DeployListRecent(ctx context.Context, arg DeployListRecentParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, deployListRecent, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Sha,
			&i.Message,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployListRunning = `-- name: DeployListRunning :many
SELECT id, environment_id, sha, message, status, started_at, finished_at FROM deployments WHERE status = 'running' ORDER BY started_at, rowid
`

func (q *Queries) DeployListRunning(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, deployListRunning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Sha,
			&i.Message,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployListRunningInEnvironment = `-- name: DeployListRunningInEnvironment :many
SELECT id, environment_id, sha, message, status, started_at, finished_at FROM deployments WHERE status = 'running' AND environment_id = ?
ORDER BY started_at, rowid
`

func (q *Queries) DeployListRunningInEnvironment(ctx context.Context, environmentID string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, deployListRunningInEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Sha,
			&i.Message,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployListSteps = `-- name: DeployListSteps :many
SELECT deployment_id, idx, node_id, label, status, started_at, applied_at, finished_at FROM deployment_steps WHERE deployment_id = ? ORDER BY idx
`

func (q *Queries) DeployListSteps(ctx context.Context, deploymentID string) ([]DeploymentStep, error) {
	rows, err := q.db.QueryContext(ctx, deployListSteps, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentStep{}
	for rows.Next() {
		var i DeploymentStep
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Idx,
			&i.NodeID,
			&i.Label,
			&i.Status,
			&i.StartedAt,
			&i.AppliedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploySetCluster = `-- name: DeploySetCluster :exec
INSERT INTO cluster (id, servers, at) VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET servers = excluded.servers, at = excluded.at
`

type DeploySetClusterParams struct {
	Servers int64
	At      int64
}

func (q *Queries) DeploySetCluster(ctx context.Context, arg DeploySetClusterParams) error {
	_, err := q.db.ExecContext(ctx, deploySetCluster, arg.Servers, arg.At)
	return err
}

const deployTrimLog = `-- name: DeployTrimLog :exec
DELETE FROM deployment_log
WHERE deployment_log.deployment_id = ?1 AND deployment_log.seq <= (
  SELECT l.seq FROM deployment_log AS l WHERE l.deployment_id = ?1
  ORDER BY l.seq DESC LIMIT 1 OFFSET ?2
)
`

type DeployTrimLogParams struct {
	DeploymentID string
	Offset       int64
}

func (q *Queries) DeployTrimLog(ctx context.Context, arg DeployTrimLogParams) error {
	_, err := q.db.ExecContext(ctx, deployTrimLog, arg.DeploymentID, arg.Offset)
	return err
}

const deployUpdate = `-- name: DeployUpdate :execrows
UPDATE deployments SET status = ?2, finished_at = ?3 WHERE id = ?1
`

type DeployUpdateParams struct {
	ID         string
	Status     string
	FinishedAt *int64
}

func (q *Queries) DeployUpdate(ctx context.Context, arg DeployUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deployUpdate, arg.ID, arg.Status, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
