// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observability.sql

package db

import (
	"context"
)

const obsCountSinks = `-- name: ObsCountSinks :one
SELECT COUNT(*) FROM log_sinks
`

func (q *Queries) ObsCountSinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, obsCountSinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const obsDeletePending = `-- name: ObsDeletePending :exec
DELETE FROM axiom_pending WHERE organization_id = ?
`

func (q *Queries) ObsDeletePending(ctx context.Context, organizationID string) error {
	_, err := q.db.ExecContext(ctx, obsDeletePending, organizationID)
	return err
}

const obsDeleteSignIn = `-- name: ObsDeleteSignIn :exec
DELETE FROM axiom_sign_ins WHERE state = ?
`

func (q *Queries) ObsDeleteSignIn(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, obsDeleteSignIn, state)
	return err
}

const obsDeleteSignInsOfOrganization = `-- name: ObsDeleteSignInsOfOrganization :exec
DELETE FROM axiom_sign_ins WHERE organization_id = ?
`

func (q *Queries) ObsDeleteSignInsOfOrganization(ctx context.Context, organizationID string) error {
	_, err := q.db.ExecContext(ctx, obsDeleteSignInsOfOrganization, organizationID)
	return err
}

const obsDeleteSink = `-- name: ObsDeleteSink :exec
DELETE FROM log_sinks WHERE organization_id = ?
`

func (q *Queries) ObsDeleteSink(ctx context.Context, organizationID string) error {
	_, err := q.db.ExecContext(ctx, obsDeleteSink, organizationID)
	return err
}

const obsGetAxiomClient = `-- name: ObsGetAxiomClient :one
SELECT client_id FROM axiom_clients WHERE redirect_uri = ?
`

func (q *Queries) ObsGetAxiomClient(ctx context.Context, redirectUri string) (string, error) {
	row := q.db.QueryRowContext(ctx, obsGetAxiomClient, redirectUri)
	var client_id string
	err := row.Scan(&client_id)
	return client_id, err
}

const obsGetOTLPKey = `-- name: ObsGetOTLPKey :one
SELECT key FROM otlp_keys WHERE environment_id = ?
`

func (q *Queries) ObsGetOTLPKey(ctx context.Context, environmentID string) (string, error) {
	row := q.db.QueryRowContext(ctx, obsGetOTLPKey, environmentID)
	var key string
	err := row.Scan(&key)
	return key, err
}

const obsGetOTLPKeyEnvironment = `-- name: ObsGetOTLPKeyEnvironment :one
SELECT environment_id FROM otlp_keys WHERE key = ?
`

func (q *Queries) ObsGetOTLPKeyEnvironment(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, obsGetOTLPKeyEnvironment, key)
	var environment_id string
	err := row.Scan(&environment_id)
	return environment_id, err
}

const obsGetOrganizationSlug = `-- name: ObsGetOrganizationSlug :one
SELECT slug FROM organizations WHERE id = ?
`

func (q *Queries) ObsGetOrganizationSlug(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, obsGetOrganizationSlug, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const obsGetPending = `-- name: ObsGetPending :one
SELECT organization_id, token, orgs, created_at FROM axiom_pending WHERE organization_id = ?
`

func (q *Queries) ObsGetPending(ctx context.Context, organizationID string) (AxiomPending, error) {
	row := q.db.QueryRowContext(ctx, obsGetPending, organizationID)
	var i AxiomPending
	err := row.Scan(
		&i.OrganizationID,
		&i.Token,
		&i.Orgs,
		&i.CreatedAt,
	)
	return i, err
}

const obsGetSignIn = `-- name: ObsGetSignIn :one
SELECT state, organization_id, client_id, verifier, redirect_uri, created_at FROM axiom_sign_ins WHERE state = ?
`

func (q *Queries) ObsGetSignIn(ctx context.Context, state string) (AxiomSignIn, error) {
	row := q.db.QueryRowContext(ctx, obsGetSignIn, state)
	var i AxiomSignIn
	err := row.Scan(
		&i.State,
		&i.OrganizationID,
		&i.ClientID,
		&i.Verifier,
		&i.RedirectUri,
		&i.CreatedAt,
	)
	return i, err
}

const obsGetSink = `-- name: ObsGetSink :one

SELECT id, organization_id, kind, domain, dataset, traces, token, org, created_at FROM log_sinks WHERE organization_id = ?
`

// Observability: log sinks, Sign in with Axiom state, OTLP ingest keys
// (docs/go/spec/observability.md). ASCII only.
func (q *Queries) ObsGetSink(ctx context.Context, organizationID string) (LogSink, error) {
	row := q.db.QueryRowContext(ctx, obsGetSink, organizationID)
	var i LogSink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Domain,
		&i.Dataset,
		&i.Traces,
		&i.Token,
		&i.Org,
		&i.CreatedAt,
	)
	return i, err
}

const obsInsertAxiomClient = `-- name: ObsInsertAxiomClient :exec
INSERT INTO axiom_clients (redirect_uri, client_id, created_at) VALUES (?, ?, ?)
ON CONFLICT (redirect_uri) DO NOTHING
`

type ObsInsertAxiomClientParams struct {
	RedirectUri string
	ClientID    string
	CreatedAt   int64
}

func (q *Queries) ObsInsertAxiomClient(ctx context.Context, arg ObsInsertAxiomClientParams) error {
	_, err := q.db.ExecContext(ctx, obsInsertAxiomClient, arg.RedirectUri, arg.ClientID, arg.CreatedAt)
	return err
}

const obsInsertOTLPKey = `-- name: ObsInsertOTLPKey :exec
INSERT INTO otlp_keys (environment_id, key, created_at) VALUES (?, ?, ?)
`

type ObsInsertOTLPKeyParams struct {
	EnvironmentID string
	Key           string
	CreatedAt     int64
}

func (q *Queries) ObsInsertOTLPKey(ctx context.Context, arg ObsInsertOTLPKeyParams) error {
	_, err := q.db.ExecContext(ctx, obsInsertOTLPKey, arg.EnvironmentID, arg.Key, arg.CreatedAt)
	return err
}

const obsInsertSignIn = `-- name: ObsInsertSignIn :exec
INSERT INTO axiom_sign_ins (state, organization_id, client_id, verifier, redirect_uri, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type ObsInsertSignInParams struct {
	State          string
	OrganizationID string
	ClientID       string
	Verifier       string
	RedirectUri    string
	CreatedAt      int64
}

func (q *Queries) ObsInsertSignIn(ctx context.Context, arg ObsInsertSignInParams) error {
	_, err := q.db.ExecContext(ctx, obsInsertSignIn,
		arg.State,
		arg.OrganizationID,
		arg.ClientID,
		arg.Verifier,
		arg.RedirectUri,
		arg.CreatedAt,
	)
	return err
}

const obsInsertSink = `-- name: ObsInsertSink :exec
INSERT INTO log_sinks (id, organization_id, kind, domain, dataset, traces, token, org, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ObsInsertSinkParams struct {
	ID             string
	OrganizationID string
	Kind           string
	Domain         string
	Dataset        string
	Traces         *string
	Token          string
	Org            *string
	CreatedAt      int64
}

func (q *Queries) ObsInsertSink(ctx context.Context, arg ObsInsertSinkParams) error {
	_, err := q.db.ExecContext(ctx, obsInsertSink,
		arg.ID,
		arg.OrganizationID,
		arg.Kind,
		arg.Domain,
		arg.Dataset,
		arg.Traces,
		arg.Token,
		arg.Org,
		arg.CreatedAt,
	)
	return err
}

const obsListDesiredNodes = `-- name: ObsListDesiredNodes :many
SELECT n.id, e.project_id FROM nodes n JOIN environments e ON e.id = n.environment_id
WHERE n.desired_image IS NOT NULL
ORDER BY n.created_at, n.id
`

type ObsListDesiredNodesRow struct {
	ID        string
	ProjectID string
}

func (q *Queries) ObsListDesiredNodes(ctx context.Context) ([]ObsListDesiredNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, obsListDesiredNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObsListDesiredNodesRow{}
	for rows.Next() {
		var i ObsListDesiredNodesRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obsListProjects = `-- name: ObsListProjects :many
SELECT id, organization_id FROM projects ORDER BY created_at, id
`

type ObsListProjectsRow struct {
	ID             string
	OrganizationID string
}

func (q *Queries) ObsListProjects(ctx context.Context) ([]ObsListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, obsListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObsListProjectsRow{}
	for rows.Next() {
		var i ObsListProjectsRow
		if err := rows.Scan(&i.ID, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obsListVariableKeys = `-- name: ObsListVariableKeys :many
SELECT key FROM variables WHERE node_id = ? ORDER BY rowid
`

func (q *Queries) ObsListVariableKeys(ctx context.Context, nodeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, obsListVariableKeys, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obsPurgePending = `-- name: ObsPurgePending :many
DELETE FROM axiom_pending WHERE created_at <= ? RETURNING organization_id
`

func (q *Queries) ObsPurgePending(ctx context.Context, createdAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, obsPurgePending, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var organization_id string
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obsPurgeSignIns = `-- name: ObsPurgeSignIns :exec
DELETE FROM axiom_sign_ins WHERE created_at <= ?
`

func (q *Queries) ObsPurgeSignIns(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, obsPurgeSignIns, createdAt)
	return err
}

const obsUpsertPending = `-- name: ObsUpsertPending :exec
INSERT INTO axiom_pending (organization_id, token, orgs, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (organization_id) DO UPDATE SET
  token = excluded.token, orgs = excluded.orgs, created_at = excluded.created_at
`

type ObsUpsertPendingParams struct {
	OrganizationID string
	Token          string
	Orgs           string
	CreatedAt      int64
}

func (q *Queries) ObsUpsertPending(ctx context.Context, arg ObsUpsertPendingParams) error {
	_, err := q.db.ExecContext(ctx, obsUpsertPending,
		arg.OrganizationID,
		arg.Token,
		arg.Orgs,
		arg.CreatedAt,
	)
	return err
}
